name: Sync to blob storage
on:
  push:
    branches:
      - master

jobs:
  sync-job:
    uses: maidannikov/yem.workflow.toazuresync/.github/workflows/sync-to-blob.yml@master
    with:
      storageAccountName: "newyemsa"
      containerName: "src"
      localFolderPath: "src"
      tenantId: "91700184-c314-4dc9-bb7e-a411df456a1e"
      clientId: "f0d7cc1a-04bc-4fed-93a8-996e80e1e816"
    secrets:
      clientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
